# This is a config for E2B sandbox template.
# You can use template ID (f7efbaier9hwmtmatth1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("f7efbaier9hwmtmatth1") # Sync sandbox
# sandbox = await AsyncSandbox.create("f7efbaier9hwmtmatth1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('f7efbaier9hwmtmatth1')

team_id = "2f49be3b-a9eb-47e0-b132-093718252814"
dockerfile = "e2b.Dockerfile"
template_id = "f7efbaier9hwmtmatth1"
