# This is a config for E2B sandbox template.
# You can use template ID (kwejtlp3ahb33o8it06d) or template name (jolli-sandbox-zf) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("jolli-sandbox-zf") # Sync sandbox
# sandbox = await AsyncSandbox.create("jolli-sandbox-zf") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('jolli-sandbox-zf')

team_id = "a2e282a8-9d29-43f2-8815-3b3deafda1a7"
dockerfile = "e2b.Dockerfile"
template_name = "jolli-sandbox-zf"
template_id = "kwejtlp3ahb33o8it06d"
